
services:
  webapp:
    build: .
    ports:
    -  8080:8080
    -  9080:9080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 3s
      retries: 3

  loki:
    image: grafana/loki
    container_name: loki
    ports:
    -  3100:3100
    depends_on:
    - webapp

  grafana:
    image: grafana/grafana:10.0.2
    container_name: grafana
    ports:
    -  9090:9090
    volumes:
    -  ./grafana.ini:/etc/grafana/grafana.ini
    -  ./ds.yaml:/etc/grafana/provisioning/datasources/ds.yaml
    depends_on:
    - loki
